import type { Metadata } from "next";
import "./globals.css";
import { Toast } from "./component/ui/Toast";

import { geistMono, inter } from "@/fonts";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${
                    inter.className ?? geistMono.variable
                } antialiased`}
            >
                <Toast />
                {children}
            </body>
        </html>
    );
}
